apiVersion: v1
kind: Secret
metadata:
  name: azure-sql-edge
  labels:
    {{- include "sqldb.labels" . | nindent 4 }}
type: Opaque
stringData:
  sql-hostname: {{ .Values.sqldb.fullnameOverride }}-service
  sql-username: {{ .Values.sqldb.database.user }}
  {{- if .Release.IsInstall }}
  sql-password: {{ randAlphaNum 20 | b64enc }}
  {{ else }}
  sql-password: {{ index (lookup "v1" "Secret" .Release.Namespace "azure-sql-edge").data "sql-password" }}
  {{ end }}
  