apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq
  namespace: infrastructure
spec:
  values:
    auth:
      securePassword: false
      existingPasswordSecret: rabbitmq
      existingErlangSecret: rabbitmq
    commonLabels:
      prometheus: add-prometheus-target
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        honorLabels: true