---
# Source: temp/templates/repository.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kube-prometheus-stack
  namespace: infrastructure
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 10m
