{
 "title": "Network Observability",
 "time": { "from": "2012-03-29T22:05:00.000Z", "to": "2012-03-29T22:06:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "collector",
    "label": "Collector",
    "query": "select distinct Collector from PacketsView"
   },
   {
    "name": "julianday",
    "label": "Julian day",
    "query": "select distinct julianDay from PacketsView"
   }
  ]
 },
 "panels": [
  {
   "title": "Data Availability",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SET QUOTED_IDENTIFIER OFF;\r\nSELECT Collector as metric, $__timeGroup(Timestamp, $__interval, NULL) as 'time', COUNT_BIG(*) as value \r\nFROM PacketsView \r\nWHERE (\"$julianday\" = \"'-1'\" OR julianDay IN ($julianday)) AND (\"$collector\" = \"''\" OR Collector IN ($collector)) \r\nGROUP BY $__timeGroup(Timestamp, $__interval, NULL), Collector\r\nORDER BY time\r\nSET QUOTED_IDENTIFIER ON;"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Packets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SET QUOTED_IDENTIFIER OFF;\r\nselect count_big(*) as 'Number of packets' from PacketsView where (\"$julianday\" = \"'-1'\" OR julianDay IN ($julianday)) AND (\"$collector\" = \"''\" OR Collector IN ($collector))\r\nSET QUOTED_IDENTIFIER ON;"
    }
   ]
  },
  {
   "title": "Data Transferred",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SET QUOTED_IDENTIFIER OFF;\r\nselect sum(cast(IpPacketSize as BIGINT)) as 'Amount of data transfered' from PacketsView where (\"$julianday\" = \"'-1'\" OR julianDay IN ($julianday)) AND (\"$collector\" = \"''\" OR Collector IN ($collector))\r\nSET QUOTED_IDENTIFIER ON;"
    }
   ]
  },
  {
   "title": "Protocols Used",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SET QUOTED_IDENTIFIER OFF;\r\nselect top 3 t.ProtocolType as 'Protocol Type', count_big(*) as 'Packet count'\r\nfrom PacketsView p\r\nleft join ProtocolTypes t on p.Protocol = t.ProtocolTypeID\r\nwhere (\"$julianday\" = \"'-1'\" OR julianDay IN ($julianday)) AND (\"$collector\" = \"''\" OR Collector IN ($collector))\r\ngroup by t.ProtocolType\r\norder by 2 desc\r\nSET QUOTED_IDENTIFIER ON;"
    }
   ]
  },
  {
   "title": "Source IPs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SET QUOTED_IDENTIFIER OFF;\r\nselect count(distinct SourceIP) as 'Number of distinct source IPs' from PacketsView where (\"$julianday\" = \"'-1'\" OR julianDay IN ($julianday)) AND (\"$collector\" = \"''\" OR Collector IN ($collector))\r\nSET QUOTED_IDENTIFIER ON;"
    }
   ]
  },
  {
   "title": "Destination IPs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SET QUOTED_IDENTIFIER OFF;\r\nselect count(distinct DestinationIP) as 'Number of distinct destination IPs' from PacketsView where (\"$julianday\" = \"'-1'\" OR julianDay IN ($julianday)) AND (\"$collector\" = \"''\" OR Collector IN ($collector))\r\nSET QUOTED_IDENTIFIER ON;"
    }
   ]
  },
  {
   "title": "Top 3 Active Ports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SET QUOTED_IDENTIFIER OFF;\r\nselect top(3) cast(SourcePort as VARCHAR(5)) as 'Source Port', convert(decimal(19,2),(sum(cast(IpPacketSize as BIGINT)) *1.0) / power(2,20)) as MB from PacketsView\r\nwhere (\"$julianday\" = \"'-1'\" OR julianDay IN ($julianday)) AND (\"$collector\" = \"''\" OR Collector IN ($collector))\r\ngroup by SourcePort\r\norder by MB desc\r\nSET QUOTED_IDENTIFIER ON;"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SET QUOTED_IDENTIFIER OFF;\r\nselect top(3) cast(DestinationPort as VARCHAR(5)) as 'Destination Port', convert(decimal(19,2),(sum(cast(IpPacketSize as BIGINT)) *1.0) / power(2,20)) as MB from PacketsView\r\nwhere (\"$julianday\" = \"'-1'\" OR julianDay IN ($julianday)) AND (\"$collector\" = \"''\" OR Collector IN ($collector))\r\ngroup by DestinationPort\r\norder by MB desc\r\nSET QUOTED_IDENTIFIER ON;"
    }
   ]
  },
  {
   "title": "Packet Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Packet Count by Data Collector",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SET QUOTED_IDENTIFIER OFF;\r\nSELECT\r\n\t Collector as metric,\r\n\t count_big(*) as value\r\n\tFROM\r\n\t PacketsView\r\n\tWHERE\r\n\t (\"$julianday\" = \"'-1'\" OR julianDay IN ($julianday)) AND (\"$collector\" = \"''\" OR Collector IN ($collector))\r\n\tGROUP BY\r\n\t Collector\r\n\tORDER BY\r\n\t Value DESC\r\nSET QUOTED_IDENTIFIER ON;"
    }
   ]
  },
  {
   "title": "Packet Count from Source to Destination IP",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SET QUOTED_IDENTIFIER OFF;\r\nDECLARE \r\n @columns NVARCHAR(MAX) = '', \r\n @sql NVARCHAR(MAX) = '';\r\n\r\n-- Select the source ips to pivot to columns\r\nSELECT \r\n @columns+=QUOTENAME(SourceIP) + ','\r\nFROM (\r\n\tSELECT DISTINCT SourceIP\r\n\tFROM PacketsView\r\n\tWHERE (\"$julianday\" = \"'-1'\" OR julianDay IN ($julianday)) AND (\"$collector\" = \"''\" OR Collector IN ($collector))\r\n) sips\r\nORDER BY SourceIP\r\n\r\n-- Remove the last comma\r\nSET @columns = LEFT(@columns, LEN(@columns) - 1);\r\n\r\n-- Construct dynamic SQL\r\nSET @sql =\"\r\nSET QUOTED_IDENTIFIER OFF;\r\nSELECT * FROM \r\n(\r\n SELECT \r\n SourceIP, \r\n DestinationIP\r\n FROM \r\n PacketsView p\r\n WHERE (\"\"\"+\"$julianday\"+\"\"\" = \"\"'-1'\"\" OR julianDay IN ($julianday)) AND (\"\"\"+\"$collector\"+\"\"\" = \"\"''\"\" OR Collector IN ($collector))\r\n) t \r\nPIVOT(\r\n COUNT_BIG(SourceIP)\r\n FOR SourceIP IN (\"+ @columns +\")\r\n) AS pivot_table\r\n\r\nORDER BY CAST(PARSENAME([DestinationIP], 4) AS INT),\r\n CAST(PARSENAME([DestinationIP], 3) AS INT),\r\n CAST(PARSENAME([DestinationIP], 2) AS INT),\r\n CAST(PARSENAME([DestinationIP], 1) AS INT);\";\r\n\r\n-- Execute the dynamic SQL\r\nEXECUTE sp_executesql @sql;\r\nSET QUOTED_IDENTIFIER ON;"
    }
   ]
  },
  {
   "title": "Traffic Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic Load by Collector",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SET QUOTED_IDENTIFIER OFF;\r\nselect sum(cast(IpPacketSize as BIGINT)) as value, Collector from PacketsView\r\n\tWHERE\r\n\t (\"$julianday\" = \"'-1'\" OR julianDay IN ($julianday)) AND (\"$collector\" = \"''\" OR Collector IN ($collector))\r\n\tGROUP BY\r\n\t Collector\r\nSET QUOTED_IDENTIFIER ON;"
    }
   ]
  },
  {
   "title": "Traffic Load by Protocol over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SET QUOTED_IDENTIFIER OFF;\r\nselect t.ProtocolType as metric, sum(cast(IpPacketSize as BIGINT)) as value, $__timeGroup(Timestamp, $__interval) as time\r\nfrom PacketsView p\r\nleft join ProtocolTypes t on p.Protocol = t.ProtocolTypeID\r\nwhere (\"$julianday\" = \"'-1'\" OR julianDay IN ($julianday)) AND (\"$collector\" = \"''\" OR Collector IN ($collector))\r\ngroup by $__timeGroup(Timestamp, $__interval), t.ProtocolType\r\norder by time\r\nSET QUOTED_IDENTIFIER ON;"
    }
   ]
  },
  {
   "title": "Traffic Load by Source IP over Time",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SET QUOTED_IDENTIFIER OFF;\r\nselect SourceIP as metric, sum(cast(IpPacketSize as BIGINT)) as value, $__timeGroup(Timestamp, $__interval) as time\r\nfrom PacketsView \r\nwhere (\"$julianday\" = \"'-1'\" OR julianDay IN ($julianday)) AND (\"$collector\" = \"''\" OR Collector IN ($collector))\r\ngroup by $__timeGroup(Timestamp, $__interval), SourceIP\r\norder by 3\r\nSET QUOTED_IDENTIFIER ON;"
    }
   ]
  },
  {
   "title": "Traffic Load by Destination IP over Time",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SET QUOTED_IDENTIFIER OFF;\r\nselect DestinationIP as metric, sum(cast(IpPacketSize as BIGINT)) as value, $__timeGroup(Timestamp, $__interval) as time\r\nfrom PacketsView \r\nwhere (\"$julianday\" = \"'-1'\" OR julianDay IN ($julianday)) AND (\"$collector\" = \"''\" OR Collector IN ($collector))\r\ngroup by $__timeGroup(Timestamp, $__interval), DestinationIP\r\norder by 3\r\nSET QUOTED_IDENTIFIER ON;"
    }
   ]
  },
  {
   "title": "Traffic Load from Source to Destination IP",
   "type": "barchart",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SET QUOTED_IDENTIFIER OFF;\r\nDECLARE \r\n @columns NVARCHAR(MAX) = '', \r\n @sql NVARCHAR(MAX) = '';\r\n\r\n-- Select the source ips to pivot to columns\r\nSELECT \r\n @columns+=QUOTENAME(SourceIP) + ','\r\nFROM (\r\n\tSELECT DISTINCT SourceIP\r\n\tFROM PacketsView\r\n\tWHERE (\"$julianday\" = \"'-1'\" OR julianDay IN ($julianday)) AND (\"$collector\" = \"''\" OR Collector IN ($collector))\r\n) sips\r\nORDER BY SourceIP\r\n\r\n-- Remove the last comma\r\nSET @columns = LEFT(@columns, LEN(@columns) - 1);\r\n\r\n-- Construct dynamic SQL\r\nSET @sql =\"\r\nSET QUOTED_IDENTIFIER OFF;\r\nSELECT * FROM \r\n(\r\n SELECT \r\n SourceIP, \r\n DestinationIP,\r\n CAST(IpPacketSize AS BIGINT) AS BigIpPacketSize\r\n FROM \r\n PacketsView p\r\n WHERE (\"\"\"+\"$julianday\"+\"\"\" = \"\"'-1'\"\" OR julianDay IN ($julianday)) AND (\"\"\"+\"$collector\"+\"\"\" = \"\"''\"\" OR Collector IN ($collector))\r\n) t \r\nPIVOT(\r\n SUM(BigIpPacketSize)\r\n FOR SourceIP IN (\"+ @columns +\")\r\n) AS pivot_table\r\n\r\nORDER BY CAST(PARSENAME([DestinationIP], 4) AS INT),\r\n CAST(PARSENAME([DestinationIP], 3) AS INT),\r\n CAST(PARSENAME([DestinationIP], 2) AS INT),\r\n CAST(PARSENAME([DestinationIP], 1) AS INT);\";\r\n\r\n-- Execute the dynamic SQL\r\nEXECUTE sp_executesql @sql;\r\nSET QUOTED_IDENTIFIER ON;"
    }
   ]
  }
 ]
}