apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{name}}-pvc
  namespace: {{coral.workspace}}-{{coral.app}}
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  volumeName: {{name}}-pv
  resources:
    requests:
      storage: 10Gi
