apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{name}}-pv
  namespace: {{coral.workspace}}-{{coral.app}}
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /opt/local-path-provisioner/netobs
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem