apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: infrastructure
spec:
  values:
    commonLabels:
      prometheus: add-prometheus-target
    hostNetwork: true
    prometheusOperator:
      admissionWebhooks:
        patch:
          podAnnotations:
            sidecar.istio.io/inject: "false"
    grafana:
      extraLabels:
        prometheus: add-prometheus-target
      sidecar:
        dashboards:
          enabled: true
          provider:
            allowUiUpdates: true
          searchNamespace: ALL
        datasources:
          enabled: true
          searchNamespace: ALL
          isDefaultDatasource: false
    kube-state-metrics:
      prometheus:
        monitor:
          additionalLabels:
            prometheus: add-prometheus-target
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
    prometheus-node-exporter:
      prometheus:
        monitor:
          additionalLabels:
            prometheus: add-prometheus-target
            